### ISSUE TITLE
Consistent labels for all prometheus output are needed

### ISSUE THREAD

**Issue by johnhtodd** [sbng/ripe-atlas-dns-tools#11]
I have found a problem with inconsistent labels.  Each metric scrape of a specific metric must contain exactly the same labels as every other metric scrape. In other words: excluding labels like "probe_address_v6" can't be done.  If a probe doesn't have a v6 address, simply leave it as equalling nothing, like this:

probe_address_v6=""

Here's the errors I'm getting on attempted imports:

Dec 16 01:41:26 res120 node_exporter: * collected metric ripe_atlas_latency label:<name:"measurement_id" value:"12016241" > label:<name:"probe_address_v4" value:"88.98.236.26" > label:<name:"probe_address_v6" value:"fd7a:115c:a1e0::3" > label:<name:"probe_asn_v4" value:"56478" > label:<name:"probe_country" value:"GB" > label:<name:"probe_id" value:"1002880" > label:<name:"probe_lat" value:"51.4775" > label:<name:"probe_lon" value:"-0.2185" > label:<name:"sample_reported_host" value:"res730" > label:<name:"sample_reported_pop" value:"lhr" > label:<name:"version" value:"4" > untyped:<value:1.589 >  has label dimensions inconsistent with previously collected metrics in the same metric family

**Comment by johnhtodd** [comment]
I'll clarify and that means that if a probe doesn't have an IPv4 address, there should still be a label of "probe_address_v4="" " in the metric line for that probe.  Similarly, any other empty label just needs to be left as empty rather than not appearing at all.

**Comment by sbng** [comment]
@johnhtodd I thought you mentioned that Prometheus doesn't like it when we have a null/nan value?

**Comment by johnhtodd** [comment]
You can have null values for labels, but not null values for the metric data. 

This works (note the null label values for v6 data in probe 99's set):

```
ripe_atlas_latency{measurement_id="12016241",probe_id="991",version="4",target_ip="9.9.9.9",probe_asn_v4="5607",probe_address_v4="94.195.182.27",probe_asn_v6="5607",probe_address_v6="2a02:c7c:a86a:3d00:220:4aff:fec7:af8e",probe_country="GB",probe_lat="51.2375",probe_lon="-0.2485",sample_reported_pop="lhr",sample_reported_host="res730"} 13.667

ripe_atlas_latency{measurement_id="12016241",probe_id="99",version="4",target_ip="9.9.9.9",probe_asn_v4="378",probe_asn_v6="",probe_address_v6="",probe_country="IL",probe_lat="32.1115",probe_lon="34.8115",sample_reported_pop="tlv",sample_reported_host="res200"} 14.12

```

But this will fail because the metrics of the same name (ripe_atlas_latency) have inconsistent label sets- some of them will be imported but the "wrong" label set ones will not.  I think the "right" label set is defined by the first label set of a metric with that name that reaches the database, and then everything after that point is compared with that first example.

```
ripe_atlas_latency{measurement_id="12016241",probe_id="991",version="4",target_ip="9.9.9.9",probe_asn_v4="5607",probe_address_v4="94.195.182.27",probe_asn_v6="5607",probe_address_v6="2a02:c7c:a86a:3d00:220:4aff:fec7:af8e",probe_country="GB",probe_lat="51.2375",probe_lon="-0.2485",sample_reported_pop="lhr",sample_reported_host="res730"} 13.667

ripe_atlas_latency{measurement_id="12016241",probe_id="99",version="4",target_ip="9.9.9.9",probe_asn_v4="378",probe_country="IL",probe_lat="32.1115",probe_lon="34.8115",sample_reported_pop="tlv",sample_reported_host="res200"} 14.12

```

This will also fail because there is no metric value:

```
ripe_atlas_latency{measurement_id="12016241",probe_id="99",version="4",target_ip="9.9.9.9",probe_asn_v4="378",probe_country="IL",probe_lat="32.1115",probe_lon="34.8115",sample_reported_pop="tlv",sample_reported_host="res200"} 
```

**Comment by sbng** [comment]
@johnhtodd, can u confirm this is ok? I will commit the changes if this is fine.

\# HELP ripe_atlas_latency The number of milliseconds for response reported by this probe for the time period requested on this measurement
\# TYPE ripe_atlas_latency gauge
ripe_atlas_latency{measurement_id="12016241",probe_id="99",version="4",target_ip="9.9.9.9",probe_asn_v4="378",probe_address_v4="",probe_asn_v6="",probe_address_v6="",probe_country="IL",probe_lat="32.1115",probe_lon="34.8115",sample_reported_pop="tlv",sample_reported_host="res200"} 14.12
ripe_atlas_latency{measurement_id="12016241",probe_id="991",version="4",target_ip="9.9.9.9",probe_asn_v4="5607",probe_address_v4="94.195.182.27",probe_asn_v6="5607",probe_address_v6="2a02:c7c:a86a:3d00:220:4aff:fec7:af8e",probe_country="GB",probe_lat="51.2375",probe_lon="-0.2485",sample_reported_pop="lhr",sample_reported_host="res730"} 13.667

**Comment by johnhtodd** [comment]
Technically, this should work - I see all the same labels between the two examples.

However, having both the probe_address_v4 AND the probe_address_v6 labels as empty is a bit unexpected, as at least one of them should be filled in.

**Comment by sbng** [comment]
@johnhtodd fixed in commit a0584c3ec8e6e0040e802166d992222b26b6bd1e please verify

**Comment by johnhtodd** [comment]
Verified, but I found a problem further downstream.  The method you've used works well, but makes querying extremely difficult (or impossible) with the variables I want to set in the graphs. 

I'd like to reverse my previous request, but only a tiny bit.  Instead of setting values to "" (null) if there is no data for the ASN field, I'd like to have you set it to "unknown".   This will allow me to match on a non-null string for some of the wildcard searches I need to do (null and non-null are separate syntax, and queries fail if I do not match on both, but that isn't possible, since I am trying to set variables to match... it's complicated, but basically I need the values set to a string  instead of set to null if there is no value you could get from the live data or the cached file.)

This also allows the condition if you can't find an ASN for either the live data OR the cached data.  It's not optimal, but at least we can still capture the information about the probe even if there is no ASN data.

**Comment by sbng** [comment]
@johnhtodd change "" value into "unknown" . commit 335a0d35ed59726f421e9dde280a517f774b2f71. Please verify
