### ISSUE TITLE
Parse POP and host for different major open recursive resolver formats

### ISSUE THREAD

**Issue by johnhtodd** [sbng/ripe-atlas-dns-tools#12]
(continuing from private conversation)

Each major open resolver has a slightly different way of reporting the POP and hostname with specific DNS queries:

Quad9 reports a hostname and a POP name in NSID for everything as an FQDN of format `<hostname>.<pop_code>.suffix1.suffix2.tld` (note: suffix1, suffix2, and TLD may change! Do not match on current values of rrdns.pch.net) and reports hostname and POP embedded in the DNS response in the same format if the request is "CH TXT id.server".  The person making the measurement can use any query. (The NSID value should be preferred by the script, as in very rare cases they might be different in the same result)  

Cloudflare reports a hash of some sort in NSID for everything (hostname?) and reports POP in the DNS response if the request is "CH TXT id.server".  The DNS response should be the value used for Cloudflare; the person making the measurement needs to ensure that the query is for "CH TXT id.server".  The hash value goes into the sample_reported_host label, and whatever is the result of the DNS query (up to 15 characters) should go into the sample_reported_pop field.

Google  reports a string containing POP name ("gpdns-<POP>") in NSID for everything, and hands back SERVFAIL if the request is "CH TXT id.server".  The person making the measurement can use any query.  The sample_reported_host field should be set to whatever is the result of the DNS query (up to 15 characters) and the sample_reported_pop should be parsed from the NSID data to just the POP code.

My suggestion is that determining which of the three methods should be used should be optional for the user when they perform the ingestion, and it should be a function on the command line or config file. An automated recognition is not required and may create unexpected results.

So command line option like this:

 --id.servermethod=[quad9,google,cloudflare]   

default: quad9

**Comment by sbng** [comment]
kindly switch to google-cloudflare-support branch.

commit f89048121eaad2d8e5c49592e3b16909bff346c0 please verify
