### ISSUE TITLE
Missing labels in many samples

### ISSUE THREAD

**Issue by johnhtodd** [sbng/ripe-atlas-dns-tools#13]
The test output data is missing from this probe.  Somehow it recorded a latency without any results for POP code?  This causes a failure in ingestion in Prometheus, since the label set doesn't match.  The labels should be null ("") or somehow there is an error collecting the data for the node and inserting it into the output.

ripe_atlas_latency{measurement_id="12016241",probe_id="50201",version="4",target_ip="9.9.9.9",probe_asn_v4="3367",probe_address_v4="98.143.253.43",probe_asn_v6="",probe_address_v6="",probe_country="CA",probe_lat="45.2975",probe_lon="-66.1925"} 7.093

**Comment by sbng** [comment]
what time is this reading taken? I am unable to see anything from probe 50201 from Jan to Apr 2023. I like to look at the live probe data to see the result we are getting,

**Comment by sbng** [comment]
@johnhtodd can I have the time of query and measurement id so I can investigate? Thanks
