### ISSUE TITLE
Repeats appearing in output

### ISSUE THREAD

**Issue by johnhtodd** [sbng/ripe-atlas-dns-tools#14]
I'm seeing repeated results in the output, which is confusing the ingestion process.

Try this:

root@ub20template:/home/jtodd/ripe-atlas-dns-tools/ripe-atlas-dns-tools# ./ra-dns-check.py 12016241 --scrape >/tmp/atlas-12016241.prom
root@ub20template:/home/jtodd/ripe-atlas-dns-tools/ripe-atlas-dns-tools# sort /tmp/atlas-12016241.prom |uniq -c|sort -n

You'll see that there are a bunch of probe samples that are exactly alike including metric values.  Some are twice, but several are many times.  One (probe id 1000515) is duplicated 6 times.

**Comment by sbng** [comment]
when changing the logic to handle clouldflare and google, a bug was introduced. I will go ahead with introducing the manual setting of --id.servermethod, so I can get rid of this logic.

**Comment by sbng** [comment]
fixed. refer to issue #12
