### ISSUE TITLE
Feature request: add "--scrape-staleness-seconds" timeout.

### ISSUE THREAD

**Issue by johnhtodd** [sbng/ripe-atlas-dns-tools#16]
With some measurements, very old data is kept in the RIPE database.  For instance, in measurement 12016241, the data from probe 1005327 was last collected in April, but we are performing the scrape today (December) and the old data is inserted into the database as if it was collected "now".  If we are not presenting the epoch timestamp with each sample, then the sample is ingested into Prometheus with the timestamp of the ingestion, which is confusing and wrong.

One way of solving this is to include the UNIX epoch seconds with each sample.  Prometheus will throw away samples that are too old (by it's estimate, which is set on the Prometheus server) and will sort the ones that are newer into their appropriate timestamp in the database.  However, this causes lots of ingestion errors on Prometheus and there is no need to clutter up the database logfiles or ingestion pipeline logfiles with old data.  Removing old data from the output will also remove dead or out-of-communication hosts from the ingestion process, which is useful.

Please add a "--scrape-staleness-seconds" setting that takes an argument of number of seconds into the past which is the maximum number that will be considered.  In other words: if a sample is more than scrape-stalenes-seconds old, then do not include it, and skip that sample.

Default should be to present all data regardless of age. The number should be able to be millions of seconds. 

Please create messages about skipping samples that are "too old" in the INFO debugging output. Include the number of seconds offset that they are (example: "Skipping probe 399231 - sample is 884323 seconds old - change scrape-staleness-seconds value to include"

**Comment by sbng** [comment]
@johnhtodd commit 658545bd4e6a75198118f0780b3762fc0f837207 Under new feature branch scrape-staleness. Please test and verify. Thanks

**Comment by sbng** [comment]
querying last year data by setting the staleness to 10 sec. This should suppress all output:
```
$ ./ra-dns-check.py --datetime1 202210080000 12016241 --scrape --scrape_staleness_seconds 10 --probes "928,975" --log_level INFO
INFO:root:Found config file at /home/sbng/.ra-dns-check.conf; reading it now...

INFO:root:Trying to access data_source 12016241 for unixtime 1665187200

INFO:root:Fetching results for Measurement 12016241,  start unixtime: 1665187200  stop unixtime: 1665791700

INFO:root:Reading the probe data dictionary as a JSON file from /home/sbng/.RIPE_atlas_probe_properties_cache_file.json...

INFO:root:Matching seen probes with probe data; will query RIPE Atlas API for probe info not in local cache...

INFO:root:cache hits: 0   cache misses: 0.

# HELP ripe_atlas_latency The number of milliseconds for response reported by this probe for the time period requested on this measurement
# TYPE ripe_atlas_latency gauge
INFO:root:Skipping probe 928 - sample is 38122851 seconds old
INFO:root:Skipping probe 975 - sample is 38122840 seconds old
```
But if we set the staleness to 38122851 + 200 seconds.
```
sbng@oat[~/.local/quad9/ripe-atlas-dns-tools]:$ ./ra-dns-check.py --datetime1 202210080000 12016241 --scrape --scrape_staleness_seconds 38123051 --probes "928,975" --log_level INFO
INFO:root:Found config file at /home/sbng/.ra-dns-check.conf; reading it now...

INFO:root:Trying to access data_source 12016241 for unixtime 1665187200

INFO:root:Fetching results for Measurement 12016241,  start unixtime: 1665187200  stop unixtime: 1665791700

INFO:root:Reading the probe data dictionary as a JSON file from /home/sbng/.RIPE_atlas_probe_properties_cache_file.json...

INFO:root:Matching seen probes with probe data; will query RIPE Atlas API for probe info not in local cache...

INFO:root:cache hits: 0   cache misses: 0.

# HELP ripe_atlas_latency The number of milliseconds for response reported by this probe for the time period requested on this measurement
# TYPE ripe_atlas_latency gauge
ripe_atlas_latency{measurement_id="12016241",probe_id="928",version="4",target_ip="9.9.9.9",probe_asn_v4="56329",probe_address_v4="216.213.161.83",probe_asn_v6="unknown",probe_address_v6="unknown",probe_country="GB",probe_lat="51.6815",probe_lon="-1.4415",sample_reported_pop="lhr",sample_reported_host="res730"} 13.433 1665222392
ripe_atlas_latency{measurement_id="12016241",probe_id="975",version="4",target_ip="9.9.9.9",probe_asn_v4="8881",probe_address_v4="92.117.54.178",probe_asn_v6="8881",probe_address_v6="unknown",probe_country="DE",probe_lat="50.9795",probe_lon="11.0405",sample_reported_pop="ber",sample_reported_host="res200"} 31.607 1665222403
```

**Comment by sbng** [comment]
commit 658545b will cover this feature.

```
$ git log --oneline | head -2                                                                               [!scrape-staleness]
00c1ed6 Update README.md documenting the new scrape stalness feature
658545b Feature --scrape-staleness-seconds - provide a staleness time to suppress scrape output that is longer then this time
```
