### ISSUE TITLE
Measurement 44040749 does not scrape correctly

### ISSUE THREAD

**Issue by johnhtodd** [sbng/ripe-atlas-dns-tools#17]
I've tried 44040749 and 44137248 and neither work.  

They are the more updated/accurate versions of the Quad9 check (daily) but not sure why they produce null results.

**Comment by sbng** [comment]
both are working in the google-cloudflare-support branch. I have converted the python case statement to if/else statements to allow lower version of python to operate on this code. Please use this google-cloudflare-support branch moving forward. Thanks.
./ra-dns-check.py 44137248 --scrape | wc -l                                                      [!google-cloudflare-support]
11421
./ra-dns-check.py 44040749 --scrape | wc -l                                                      [!google-cloudflare-support]
11389

@johnhtodd

**Comment by johnhtodd** [comment]
Still doesn't quite seem to work:

```
root@ub20template:/home/jtodd/ripe-atlas-dns-tools# git clone -b google-cloudflare-support https://github.com/sbng/ripe-atlas-dns-tools.git
Cloning into 'ripe-atlas-dns-tools'...
remote: Enumerating objects: 379, done.
remote: Counting objects: 100% (184/184), done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 379 (delta 121), reused 146 (delta 94), pack-reused 195
Receiving objects: 100% (379/379), 4.84 MiB | 6.59 MiB/s, done.
Resolving deltas: 100% (241/241), done.
root@ub20template:/home/jtodd/ripe-atlas-dns-tools# cd ripe-atlas-dns-tools
root@ub20template:/home/jtodd/ripe-atlas-dns-tools/ripe-atlas-dns-tools# ./ra-dns-check.py 44137248 --scrape >/tmp/atlas-44137248.prom
  File "./ra-dns-check.py", line 1009
    match args[0].id_servermethod:
          ^
SyntaxError: invalid syntax
root@ub20template:/home/jtodd/ripe-atlas-dns-tools/ripe-atlas-dns-tools#

```

**Comment by sbng** [comment]
![image](https://github.com/sbng/ripe-atlas-dns-tools/assets/7722519/5cfbf2fc-f865-484b-8f2f-9499fa102ac0)

**Comment by sbng** [comment]
@johnhtodd My bad. I forgotten to push the lastetst changes. Apologies...Please try again

**Comment by sbng** [comment]
sbng@oat[~/.local/quad9/ripe-atlas-dns-tools]:$ git log --oneline | head -4                                                                       [google-cloudflare-support]
9e4ea85 Convert python case statement to if/else for users with python version < 3.10
8ebffbe Merge branch 'Quad9DNS:main' into google-cloudflare-support
335a0d3 Populate 'unknown' as value for ''(null) value in the --scrape output
6912ea6 update requirements.txt and README.md to include argcomplete module for autocomplete

@johnhtodd u should see commit 9e4ea85

**Comment by sbng** [comment]
![image](https://github.com/sbng/ripe-atlas-dns-tools/assets/7722519/c54a527c-7c00-447d-b804-475889dce1df)

**Comment by sbng** [comment]
for the old dev-ripe-dns branch. It's code to support on "ch txt" and extract the pop/host code from it. While the new google support branch. it's code to extract pop/nsid via abuf decode. Mesurement id 44137248 do not have a "answer" section, hence all the result will not get printed out. Please move to google support branch so we can start extracting opo/host code from the abuf decode.
