### ISSUE TITLE
Change single ticmarks to quotes, change colons to =, remove label quotes

### ISSUE THREAD

**Issue by johnhtodd** [sbng/ripe-atlas-dns-tools#3]
Need to shift to standardized Prometheus format for label declarations and quoting:

So this:

ripe_atlas_latency{'measurement_id':64573001,'probe_id':63075,'version':4,'probe_asn':269750,'probe_ip':'190.8.168.42','country':'VE','loc':'qmia2','host':'res120','lat':10.6395,'long':-71.6095} 42.037 1701997451

becomes this:

ripe_atlas_latency{measurement_id="64573001",probe_id="63075",version="4",probe_asn="269750",probe_ip="190.8.168.42",country="VE",loc="qmia2",host="res120",lat="10.6395",long="-71.6095"} 42.037 1701997451

**Comment by sbng** [comment]
@johnhtodd updated to the required format. Please help me verify before I close issue 3 and start working on ipv6 issue. Thanks.

https://github.com/sbng/ripe-atlas-dns-tools/commit/a80e4056e72db984b6767b2babe421dd33ca0d81
