### ISSUE TITLE
Add optional sample timing flag

### ISSUE THREAD

**Issue by johnhtodd** [sbng/ripe-atlas-dns-tools#6]
Currently, the default behavior for "--scrape" is to include the timestamp of the probe sample time according to RIPE.  This should be optional.

I'd say something like this to be added to the help summary:

"--include-probe-timestamp   - include the epoch seconds of the reported timestamp as delivered by RIPE Atlas at the end of the Prometheus-style formatted output.  Default is to not include timestamp."

**Comment by sbng** [comment]
@johnhtodd I use snake_case instead. Hence --include-probe-timestamp would be --include_probe_timestamp. This is for consistency with the result of the ripe arguments from original script.

**Comment by sbng** [comment]
commit 043365dedfb1cec88fdf1aa883d66f5343079928
