### ISSUE TITLE
Modify label names for clarity and non-conflict

### ISSUE THREAD

**Issue by johnhtodd** [sbng/ripe-atlas-dns-tools#7]
After more consideration, I think the label names are prone to conflict with other labels and are not clear enough by themselves, and need to be made more unique.

"loc" should change to "sample_reported_pop"
"host" should change to "sample_reported_host"
"country" should change to "probe_country"
"lat" should change to "probe_lat"
"lon" should change to "probe_lon"

**Comment by sbng** [comment]
commit b3e7e5fbcd9fa5f3accf8faa6e3e6002d0e86480
