### ISSUE TITLE
Failure due to cache file problems

### ISSUE THREAD

**Issue by johnhtodd** [sbng/ripe-atlas-dns-tools#8]
I'm starting "clean" with no cache files in my directory.  I get this:

root@ub20template:/home/jtodd/ripe-atlas-dns-tools/ripe-atlas-dns-tools# ./ra-dns-check.py 44137248 --scrape
CRITICAL:root:Cannot read probe data from file: /root/.RIPE_atlas_probe_properties_cache_file.json

root@ub20template:/home/jtodd/ripe-atlas-dns-tools/ripe-atlas-dns-tools#

Why is this not created?

Also: if I am running multiple scrapes using multiple measurement IDs, does the probe properties file get updated with ALL the probes across both measurements, or does it fail in some unusual way?  If required, perhaps put the measurement number in the filename so a unique file is created for each probe set?   I don't know how it currently works.

If I try copying an old cache file into ~root/.RIPE_atlas_probe_properties_cache_file.json  then I get this:

root@ub20template:/home/jtodd/ripe-atlas-dns-tools/ripe-atlas-dns-tools# ./ra-dns-check.py 44137248 --scrape
Traceback (most recent call last):
  File "./ra-dns-check.py", line 944, in <module>
    p_probe_properties = load_probe_properties([dnsresult[x]['prb_id'] for x in range(len(dnsresult))], config['ripe_atlas_probe_properties_json_cache_file'])
  File "./ra-dns-check.py", line 889, in load_probe_properties
    matched_probe_info[i] = all_probes_dict[i]
KeyError: '1006936'
root@ub20template:/home/jtodd/ripe-atlas-dns-tools/ripe-atlas-dns-tools#

**Comment by sbng** [comment]
Apparently the RIPE script doesn't force the cache to regenerate even when the cache file is missing :-( I have rectify this behavior.  commit 40b895ef7a984a79978dbc4e9b48874323549c29. Please check

**Comment by johnhtodd** [comment]
This worked and built a new cache file!  So that's good.   Running against the Cloudflare (12016253) and Quad9 (12016241) measurements I receive no error.  

But running against the Google measurement (43869257) I get this:

```
root@ub20template:/home/jtodd/ripe-atlas-dns-tools/ripe-atlas-dns-tools# ./ra-dns-check.py 43869257 --scrape
Traceback (most recent call last):
  File "./ra-dns-check.py", line 952, in <module>
    p_probe_properties = load_probe_properties([dnsresult[x]['prb_id'] for x in range(len(dnsresult))], config['ripe_atlas_probe_properties_json_cache_file'])
  File "./ra-dns-check.py", line 897, in load_probe_properties
    matched_probe_info[i] = all_probes_dict[i]
KeyError: '1006975'
root@ub20template:/home/jtodd/ripe-atlas-dns-tools/ripe-atlas-dns-tools#

```
