### ISSUE TITLE
Data safety check in sample collected fields

### ISSUE THREAD

**Issue by johnhtodd** [sbng/ripe-atlas-dns-tools#9]
Can you please check the safety of the data being presented in the sample_reported_pop and sample_reported_host field.

Remove everything other than a-Z, 0-9, -, _, ., and " " for good measure. I see ways that could be abused, otherwise.

**Comment by johnhtodd** [comment]
More explanation on this:  What if someone put the following string in their NSID value (including the quotes)

hi,",probe_id=12345,job="whatever"\.rrdns.pch.net

That could result in a metric that looks like this:

ripe_atlas_latency{measurement_id="12016241",probe_id="99",version="4",target_ip="9.9.9.9",probe_asn_v4="378",probe_country="IL",probe_lat="32.1115",probe_lon="34.8115",sample_reported_pop="hi,",probe_id=12345,job="whatever",\",sample_reported_host="res200"} 14.12

This would result in unexpected labels appearing in the data stream from external sources.  My particular example may or may not work (at a minimum, it would be rejected and the sample would be discarded) but there is risk here for clever injection of characters into those strings which has meaning as parsed by other components.  Standard SQL injection attack methods.

This is a really bad security and stability risk.  So I'd like to see the strings that are pulled from remote systems (sample_reported_pop and sample_reported host) be stripped of all characters except for a small set of characters that cannot be interpreted by string parsers in unexpected ways further down the pipeline.

In my example above, the attack string would be sanitized to:

hiprobe_id12345jobwhatever.rrdns.pch.net

**Comment by sbng** [comment]
Thanks for your illustration. The sanitize_string function was written to cover this. Kindly switch to google-cloudflare-support branch commit f89048121eaad2d8e5c49592e3b16909bff346c0 to verify

**Comment by sbng** [comment]
sanitize_string() function will cover this use case.
